language: android
cache: yarn
android:
    components:
        - build-tools-28.0.3
install: 
- wget -O - https://raw.githubusercontent.com/VOID001/wine-travis/master/install-wine.sh | bash
- yes | sdkmanager tools > /dev/null
- yes | sdkmanager --licenses > /dev/null
- nvm install 11
- yarn
- yarn global add cordova
- yarn cordova-prepare
script:
- yarn build
- yarn cordova-build-android
- yarn electron:build-linux
- yarn electron:build-windows
after_deploy: npx semantic-release
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: dist
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
