language: android
cache: yarn
install: 
- nvm install 11
- yarn
- yarn global add cordova
- yarn cordova-prepare
script:
- yarn build
- yarn cordova-build-android
- yarn electron:build
after_deploy: npx semantic-release
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: dist
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
