language: android
cache:
  yarn: true
  directories:
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder
android:
    components:
        - build-tools-28.0.3
install: 
- yes | sdkmanager tools > /dev/null
- yes | sdkmanager --licenses > /dev/null
- nvm install 11
- docker pull electronuserland/electron-builder:wine
- yarn
- yarn global add cordova
- yarn cordova-prepare
script:
- yarn build
- yarn cordova-build-android
- yarn docker-all
after_deploy: npx semantic-release
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: dist
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
